# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createuser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormTambahUser(object):
    def setupUi(self, FormTambahUser):
        FormTambahUser.setObjectName("FormTambahUser")
        FormTambahUser.resize(689, 798)
        FormTambahUser.setStyleSheet("\n"
"    QWidget { background-color: #121212; color: #E0E0E0; font-family: \'Segoe UI\', sans-serif; font-size: 11pt; }\n"
"    QGroupBox { background-color: #1E1E1E; border: 1px solid #333333; border-radius: 12px; margin-top: 24px; font-weight: bold; }\n"
"    QGroupBox::title { subcontrol-origin: margin; left: 10px; padding: 0 5px; color: #82B1FF; }\n"
"    QLabel { color: #B0B0B0; }\n"
"    QLineEdit, QComboBox { background-color: #2D2D2D; border: 1px solid #404040; border-radius: 8px; padding: 8px; color: white; }\n"
"    QLineEdit:focus, QComboBox:focus { border: 2px solid #2962FF; }\n"
"    QPushButton { background-color: #333333; border: 1px solid #444444; border-radius: 8px; padding: 10px 20px; color: white; font-weight: bold; }\n"
"    QPushButton:hover { background-color: #424242; }\n"
"    QPushButton#pushButton_simpan_user { background-color: #2962FF; border: none; }\n"
"    QPushButton#pushButton_simpan_user:hover { background-color: #1565C0; }\n"
"    QPushButton#pushButton_cancel, QPushButton#pushButton_kembali { background-color: #D32F2F; border: none; }\n"
"    QPushButton#pushButton_cancel:hover, QPushButton#pushButton_kembali:hover { background-color: #B71C1C; }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(FormTambahUser)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(FormTambahUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.groupBox_tambah_user = QtWidgets.QGroupBox(FormTambahUser)
        self.groupBox_tambah_user.setObjectName("groupBox_tambah_user")
        self.formLayout = QtWidgets.QVBoxLayout(self.groupBox_tambah_user)
        self.formLayout.setObjectName("formLayout")
        self.label_nama_2 = QtWidgets.QLabel(self.groupBox_tambah_user)
        self.label_nama_2.setObjectName("label_nama_2")
        self.formLayout.addWidget(self.label_nama_2)
        self.lineEdit_nama_2 = QtWidgets.QLineEdit(self.groupBox_tambah_user)
        self.lineEdit_nama_2.setObjectName("lineEdit_nama_2")
        self.formLayout.addWidget(self.lineEdit_nama_2)
        self.label_nama = QtWidgets.QLabel(self.groupBox_tambah_user)
        self.label_nama.setObjectName("label_nama")
        self.formLayout.addWidget(self.label_nama)
        self.lineEdit_nama = QtWidgets.QLineEdit(self.groupBox_tambah_user)
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.formLayout.addWidget(self.lineEdit_nama)
        self.label_username = QtWidgets.QLabel(self.groupBox_tambah_user)
        self.label_username.setObjectName("label_username")
        self.formLayout.addWidget(self.label_username)
        self.lineEdit_username = QtWidgets.QLineEdit(self.groupBox_tambah_user)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.formLayout.addWidget(self.lineEdit_username)
        self.label_password = QtWidgets.QLabel(self.groupBox_tambah_user)
        self.label_password.setObjectName("label_password")
        self.formLayout.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(self.groupBox_tambah_user)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.formLayout.addWidget(self.lineEdit_password)
        self.label_level = QtWidgets.QLabel(self.groupBox_tambah_user)
        self.label_level.setObjectName("label_level")
        self.formLayout.addWidget(self.label_level)
        self.comboBox_level = QtWidgets.QComboBox(self.groupBox_tambah_user)
        self.comboBox_level.setObjectName("comboBox_level")
        self.comboBox_level.addItem("")
        self.comboBox_level.addItem("")
        self.formLayout.addWidget(self.comboBox_level)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.addItem(spacerItem)
        self.pushButton_simpan_user = QtWidgets.QPushButton(self.groupBox_tambah_user)
        self.pushButton_simpan_user.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_simpan_user.setObjectName("pushButton_simpan_user")
        self.formLayout.addWidget(self.pushButton_simpan_user)
        self.verticalLayout.addWidget(self.groupBox_tambah_user)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_kembali = QtWidgets.QPushButton(FormTambahUser)
        self.pushButton_kembali.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_kembali.setObjectName("pushButton_kembali")
        self.horizontalLayout.addWidget(self.pushButton_kembali)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(FormTambahUser)
        QtCore.QMetaObject.connectSlotsByName(FormTambahUser)

    def retranslateUi(self, FormTambahUser):
        _translate = QtCore.QCoreApplication.translate
        FormTambahUser.setWindowTitle(_translate("FormTambahUser", "Tambah User Baru"))
        self.label_title.setStyleSheet(_translate("FormTambahUser", "font-size: 36px; font-weight: bold; color: white; margin-bottom: 20px;"))
        self.label_title.setText(_translate("FormTambahUser", "Tambah User"))
        self.groupBox_tambah_user.setTitle(_translate("FormTambahUser", "Data User Baru"))
        self.label_nama_2.setText(_translate("FormTambahUser", "ID User:"))
        self.lineEdit_nama_2.setPlaceholderText(_translate("FormTambahUser", "Contoh: USR001"))
        self.label_nama.setText(_translate("FormTambahUser", "Nama Lengkap:"))
        self.lineEdit_nama.setPlaceholderText(_translate("FormTambahUser", "Contoh: Ruli"))
        self.label_username.setText(_translate("FormTambahUser", "Username:"))
        self.lineEdit_username.setPlaceholderText(_translate("FormTambahUser", "Username untuk login"))
        self.label_password.setText(_translate("FormTambahUser", "Password:"))
        self.lineEdit_password.setPlaceholderText(_translate("FormTambahUser", "Masukkan password kuat"))
        self.label_level.setText(_translate("FormTambahUser", "Level Akses:"))
        self.comboBox_level.setItemText(0, _translate("FormTambahUser", "User"))
        self.comboBox_level.setItemText(1, _translate("FormTambahUser", "Admin"))
        self.pushButton_simpan_user.setText(_translate("FormTambahUser", "💾 Simpan Data"))
        self.pushButton_kembali.setText(_translate("FormTambahUser", "Kembali"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormTambahUser = QtWidgets.QWidget()
    ui = Ui_FormTambahUser()
    ui.setupUi(FormTambahUser)
    FormTambahUser.show()
    sys.exit(app.exec_())
