# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listuser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

# Tambahan untuk menghilangkan error warning merah di terminal
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

class Ui_FormListUser(object):
    def setupUi(self, FormListUser):
        FormListUser.setObjectName("FormListUser")
        FormListUser.resize(900, 800)
        # SAYA TAMBAHKAN STYLE KHUSUS UNTUK btnKembali DI SINI
        FormListUser.setStyleSheet("\n"
"    QWidget { background-color: #121212; color: #E0E0E0; font-family: \'Segoe UI\', sans-serif; font-size: 11pt; }\n"
"    \n"
"    /* CARD */\n"
"    QFrame#card { background-color: #1E1E1E; border: 1px solid #333333; border-radius: 12px; }\n"
"    \n"
"    /* INPUTS */\n"
"    QLineEdit, QComboBox { \n"
"        background-color: #2D2D2D; \n"
"        border: 1px solid #404040; \n"
"        border-radius: 8px; \n"
"        padding: 6px 12px; \n"
"        color: white; \n"
"    }\n"
"    QLineEdit:focus, QComboBox:focus { border: 2px solid #2962FF; }\n"
"\n"
"    /* TABLE */\n"
"    QTableWidget { background-color: #1E1E1E; border: 1px solid #333333; gridline-color: #2C2C2C; border-radius: 8px; }\n"
"    QHeaderView::section { background-color: #252525; padding: 8px; border: none; border-bottom: 2px solid #2962FF; color: white; font-weight: bold; }\n"
"    \n"
"    /* BUTTONS */\n"
"    QPushButton { background-color: #333333; border: 1px solid #444444; border-radius: 8px; padding: 10px; color: white; font-weight: bold; }\n"
"    QPushButton:hover { background-color: #424242; }\n"
"    \n"
"    /* ACTION BUTTONS */\n"
"    QPushButton#btnTambah, QPushButton#btnUpdate { background-color: #2962FF; border: none; }\n"
"    QPushButton#btnTambah:hover, QPushButton#btnUpdate:hover { background-color: #1565C0; }\n"
"    QPushButton#btnHapus { background-color: #D32F2F; border: none; }\n"
"    QPushButton#btnHapus:hover { background-color: #B71C1C; }\n"
"    \n"
"    /* TOMBOL KEMBALI (BARU) */\n"
"    QPushButton#btnKembali { background-color: #757575; border: none; }\n"
"    QPushButton#btnKembali:hover { background-color: #616161; }\n"
"    \n"
"    /* SEARCH BUTTON */\n"
"    QPushButton#btnCari { background-color: #2D2D2D; padding: 6px 12px; }\n"
"    QPushButton#btnCari:hover { background-color: #383838; }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(FormListUser)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.card = QtWidgets.QFrame(self.centralwidget)
        self.card.setObjectName("card")
        self.cardLayout = QtWidgets.QVBoxLayout(self.card)
        self.cardLayout.setObjectName("cardLayout")
        self.label = QtWidgets.QLabel(self.card)
        self.label.setObjectName("label")
        self.cardLayout.addWidget(self.label)
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setContentsMargins(-1, -1, -1, 10)
        self.filterLayout.setObjectName("filterLayout")
        self.lineEdit_search = QtWidgets.QLineEdit(self.card)
        self.lineEdit_search.setMinimumSize(QtCore.QSize(250, 35))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.filterLayout.addWidget(self.lineEdit_search)
        self.comboBox_filterLevel = QtWidgets.QComboBox(self.card)
        self.comboBox_filterLevel.setMinimumSize(QtCore.QSize(150, 35))
        self.comboBox_filterLevel.setObjectName("comboBox_filterLevel")
        self.comboBox_filterLevel.addItem("")
        self.comboBox_filterLevel.addItem("")
        self.comboBox_filterLevel.addItem("")
        self.filterLayout.addWidget(self.comboBox_filterLevel)
        self.btnCari = QtWidgets.QPushButton(self.card)
        self.btnCari.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCari.setObjectName("btnCari")
        self.filterLayout.addWidget(self.btnCari)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.filterLayout.addItem(spacerItem)
        self.cardLayout.addLayout(self.filterLayout)
        self.tableUser = QtWidgets.QTableWidget(self.card)
        self.tableUser.setAlternatingRowColors(True)
        self.tableUser.setColumnCount(5)
        self.tableUser.setObjectName("tableUser")
        self.tableUser.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(4, item)
        self.cardLayout.addWidget(self.tableUser)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btnTambah = QtWidgets.QPushButton(self.card)
        self.btnTambah.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnTambah.setObjectName("btnTambah")
        self.buttonLayout.addWidget(self.btnTambah)
        self.btnUpdate = QtWidgets.QPushButton(self.card)
        self.btnUpdate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnUpdate.setObjectName("btnUpdate")
        self.buttonLayout.addWidget(self.btnUpdate)
        self.btnHapus = QtWidgets.QPushButton(self.card)
        self.btnHapus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnHapus.setObjectName("btnHapus")
        self.buttonLayout.addWidget(self.btnHapus)
        
        # --- PENAMBAHAN TOMBOL KEMBALI DI SINI ---
        self.btnKembali = QtWidgets.QPushButton(self.card)
        self.btnKembali.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnKembali.setObjectName("btnKembali")
        self.buttonLayout.addWidget(self.btnKembali)
        # -----------------------------------------

        self.cardLayout.addLayout(self.buttonLayout)
        self.mainLayout.addWidget(self.card)
        FormListUser.setCentralWidget(self.centralwidget)

        self.retranslateUi(FormListUser)
        QtCore.QMetaObject.connectSlotsByName(FormListUser)

    def retranslateUi(self, FormListUser):
        _translate = QtCore.QCoreApplication.translate
        FormListUser.setWindowTitle(_translate("FormListUser", "Daftar User"))
        self.label.setStyleSheet(_translate("FormListUser", "font-size: 18pt; font-weight: bold; color: white; margin-bottom: 10px;"))
        self.label.setText(_translate("FormListUser", "👤 Manajemen User"))
        self.lineEdit_search.setPlaceholderText(_translate("FormListUser", "🔍 Cari Nama atau Username..."))
        self.comboBox_filterLevel.setPlaceholderText(_translate("FormListUser", "Semua Level"))
        self.comboBox_filterLevel.setItemText(0, _translate("FormListUser", "Semua Level"))
        self.comboBox_filterLevel.setItemText(1, _translate("FormListUser", "Admin"))
        self.comboBox_filterLevel.setItemText(2, _translate("FormListUser", "User"))
        self.btnCari.setText(_translate("FormListUser", "Cari"))
        item = self.tableUser.horizontalHeaderItem(0)
        item.setText(_translate("FormListUser", "ID"))
        item = self.tableUser.horizontalHeaderItem(1)
        item.setText(_translate("FormListUser", "Nama"))
        item = self.tableUser.horizontalHeaderItem(2)
        item.setText(_translate("FormListUser", "Username"))
        item = self.tableUser.horizontalHeaderItem(3)
        item.setText(_translate("FormListUser", "Level"))
        item = self.tableUser.horizontalHeaderItem(4)
        item.setText(_translate("FormListUser", "Password"))
        self.btnTambah.setText(_translate("FormListUser", "+ Tambah User"))
        self.btnUpdate.setText(_translate("FormListUser", "✎ Update User"))
        self.btnHapus.setText(_translate("FormListUser", "🗑 Hapus User"))
        
        # LABEL TOMBOL KEMBALI
        self.btnKembali.setText(_translate("FormListUser", "⬅ Kembali"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormListUser = QtWidgets.QMainWindow()
    ui = Ui_FormListUser()
    ui.setupUi(FormListUser)
    FormListUser.show()
    sys.exit(app.exec_())