# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jajalmanajemenpenj.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormManajemenPenjualan(object):
    def setupUi(self, FormManajemenPenjualan):
        FormManajemenPenjualan.setObjectName("FormManajemenPenjualan")
        FormManajemenPenjualan.resize(900, 800)
        FormManajemenPenjualan.setStyleSheet("\n"
"    QWidget { background-color: #121212; color: #FFFFFF; font-family: \'Segoe UI\', sans-serif; font-size: 11pt; }\n"
"    \n"
"    /* CARD */\n"
"    QFrame#card { background-color: #1E1E1E; border-radius: 12px; border: 1px solid #333333; }\n"
"    \n"
"    /* INPUTS */\n"
"    QLineEdit, QDateEdit { \n"
"        background-color: #2D2D2D; \n"
"        border: 1px solid #404040; \n"
"        border-radius: 8px; \n"
"        padding: 6px 12px; \n"
"        color: white; \n"
"    }\n"
"    QLineEdit:focus, QDateEdit:focus { border: 2px solid #82B1FF; }\n"
"\n"
"    /* TABLE */\n"
"    QTableWidget { background-color: #1E1E1E; border: 1px solid #333333; gridline-color: #2C2C2C; border-radius: 8px; }\n"
"    QHeaderView::section { background-color: #252525; padding: 10px; border: none; border-bottom: 2px solid #2962FF; font-weight: bold; color: white; }\n"
"    \n"
"    /* LABELS */\n"
"    QLabel { font-weight: bold; color: #E0E0E0; }\n"
"    \n"
"    /* FILTER BUTTON (Blue) */\n"
"    QPushButton#btnFilter { \n"
"        background-color: #2962FF; \n"
"        color: white; \n"
"        border: none; \n"
"        border-radius: 8px; \n"
"        padding: 8px 16px; \n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton#btnFilter:hover { background-color: #1565C0; }\n"
"\n"
"    /* Back Button (Red) */\n"
"    QPushButton#btnKembali {\n"
"        background-color: #D32F2F;\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 8px; \n"
"        padding: 10px 20px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton#btnKembali:hover { background-color: #B71C1C; }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(FormManajemenPenjualan)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.card = QtWidgets.QFrame(self.centralwidget)
        self.card.setObjectName("card")
        self.cardLayout = QtWidgets.QVBoxLayout(self.card)
        self.cardLayout.setObjectName("cardLayout")
        self.label = QtWidgets.QLabel(self.card)
        self.label.setObjectName("label")
        self.cardLayout.addWidget(self.label)
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setContentsMargins(-1, -1, -1, 10)
        self.filterLayout.setObjectName("filterLayout")
        self.lineEdit_search = QtWidgets.QLineEdit(self.card)
        self.lineEdit_search.setMinimumSize(QtCore.QSize(200, 35))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.filterLayout.addWidget(self.lineEdit_search)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.filterLayout.addItem(spacerItem)
        self.label_dari = QtWidgets.QLabel(self.card)
        self.label_dari.setObjectName("label_dari")
        self.filterLayout.addWidget(self.label_dari)
        self.dateEdit_start = QtWidgets.QDateEdit(self.card)
        self.dateEdit_start.setMinimumSize(QtCore.QSize(110, 35))
        self.dateEdit_start.setCalendarPopup(True)
        self.dateEdit_start.setDate(QtCore.QDate(2024, 1, 1))
        self.dateEdit_start.setObjectName("dateEdit_start")
        self.filterLayout.addWidget(self.dateEdit_start)
        self.label_sampai = QtWidgets.QLabel(self.card)
        self.label_sampai.setObjectName("label_sampai")
        self.filterLayout.addWidget(self.label_sampai)
        self.dateEdit_end = QtWidgets.QDateEdit(self.card)
        self.dateEdit_end.setMinimumSize(QtCore.QSize(110, 35))
        self.dateEdit_end.setCalendarPopup(True)
        self.dateEdit_end.setDate(QtCore.QDate(2024, 12, 31))
        self.dateEdit_end.setObjectName("dateEdit_end")
        self.filterLayout.addWidget(self.dateEdit_end)
        self.btnFilter = QtWidgets.QPushButton(self.card)
        self.btnFilter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFilter.setObjectName("btnFilter")
        self.filterLayout.addWidget(self.btnFilter)
        self.cardLayout.addLayout(self.filterLayout)
        self.tablePenjualan = QtWidgets.QTableWidget(self.card)
        self.tablePenjualan.setAlternatingRowColors(True)
        self.tablePenjualan.setColumnCount(7)
        self.tablePenjualan.setObjectName("tablePenjualan")
        self.tablePenjualan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePenjualan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePenjualan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePenjualan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePenjualan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePenjualan.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePenjualan.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePenjualan.setHorizontalHeaderItem(6, item)
        self.cardLayout.addWidget(self.tablePenjualan)
        self.mainLayout.addWidget(self.card)
        self.bottomLayout = QtWidgets.QHBoxLayout()
        self.bottomLayout.setObjectName("bottomLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout.addItem(spacerItem1)
        self.btnKembali = QtWidgets.QPushButton(self.centralwidget)
        self.btnKembali.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnKembali.setObjectName("btnKembali")
        self.bottomLayout.addWidget(self.btnKembali)
        self.mainLayout.addLayout(self.bottomLayout)
        FormManajemenPenjualan.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FormManajemenPenjualan)
        self.statusbar.setObjectName("statusbar")
        FormManajemenPenjualan.setStatusBar(self.statusbar)

        self.retranslateUi(FormManajemenPenjualan)
        QtCore.QMetaObject.connectSlotsByName(FormManajemenPenjualan)

    def retranslateUi(self, FormManajemenPenjualan):
        _translate = QtCore.QCoreApplication.translate
        FormManajemenPenjualan.setWindowTitle(_translate("FormManajemenPenjualan", "Manajemen Penjualan"))
        self.label.setStyleSheet(_translate("FormManajemenPenjualan", "font-size: 18pt; margin-bottom: 10px; color: #82B1FF;"))
        self.label.setText(_translate("FormManajemenPenjualan", "📑 Data Penjualan"))
        self.lineEdit_search.setPlaceholderText(_translate("FormManajemenPenjualan", "🔍 Cari Kode/Barang..."))
        self.label_dari.setText(_translate("FormManajemenPenjualan", "Dari:"))
        self.dateEdit_start.setDisplayFormat(_translate("FormManajemenPenjualan", "dd/MM/yyyy"))
        self.label_sampai.setText(_translate("FormManajemenPenjualan", "Sampai:"))
        self.dateEdit_end.setDisplayFormat(_translate("FormManajemenPenjualan", "dd/MM/yyyy"))
        self.btnFilter.setText(_translate("FormManajemenPenjualan", "Tampilkan"))
        item = self.tablePenjualan.horizontalHeaderItem(0)
        item.setText(_translate("FormManajemenPenjualan", "Kode"))
        item = self.tablePenjualan.horizontalHeaderItem(1)
        item.setText(_translate("FormManajemenPenjualan", "Nama"))
        item = self.tablePenjualan.horizontalHeaderItem(2)
        item.setText(_translate("FormManajemenPenjualan", "Ukuran"))
        item = self.tablePenjualan.horizontalHeaderItem(3)
        item.setText(_translate("FormManajemenPenjualan", "Jenis"))
        item = self.tablePenjualan.horizontalHeaderItem(4)
        item.setText(_translate("FormManajemenPenjualan", "Harga"))
        item = self.tablePenjualan.horizontalHeaderItem(5)
        item.setText(_translate("FormManajemenPenjualan", "Jumlah"))
        item = self.tablePenjualan.horizontalHeaderItem(6)
        item.setText(_translate("FormManajemenPenjualan", "Total"))
        self.btnKembali.setText(_translate("FormManajemenPenjualan", "Kembali"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormManajemenPenjualan = QtWidgets.QMainWindow()
    ui = Ui_FormManajemenPenjualan()
    ui.setupUi(FormManajemenPenjualan)
    FormManajemenPenjualan.show()
    sys.exit(app.exec_())
