# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateuser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormUpdateUser(object):
    def setupUi(self, FormUpdateUser):
        FormUpdateUser.setObjectName("FormUpdateUser")
        FormUpdateUser.resize(691, 797)
        FormUpdateUser.setStyleSheet("\n"
"    QWidget { background-color: #121212; color: #E0E0E0; font-family: \'Segoe UI\', sans-serif; font-size: 11pt; }\n"
"    QGroupBox { background-color: #1E1E1E; border: 1px solid #333333; border-radius: 12px; margin-top: 24px; font-weight: bold; }\n"
"    QGroupBox::title { subcontrol-origin: margin; left: 10px; padding: 0 5px; color: #82B1FF; }\n"
"    QLabel { color: #B0B0B0; }\n"
"    QLineEdit, QComboBox { background-color: #2D2D2D; border: 1px solid #404040; border-radius: 8px; padding: 8px; color: white; }\n"
"    QLineEdit:focus, QComboBox:focus { border: 2px solid #2962FF; }\n"
"    QPushButton { background-color: #333333; border: 1px solid #444444; border-radius: 8px; padding: 10px; color: white; font-weight: bold; }\n"
"    QPushButton:hover { background-color: #424242; }\n"
"    QPushButton#pushButton_cari, QPushButton#pushButton_update_user { background-color: #2962FF; border: none; }\n"
"    QPushButton#pushButton_cari:hover, QPushButton#pushButton_update_user:hover { background-color: #1565C0; }\n"
"    QPushButton#pushButton_cancel, QPushButton#pushButton_kembali { background-color: #D32F2F; border: none; }\n"
"   ")
        self.mainLayout = QtWidgets.QVBoxLayout(FormUpdateUser)
        self.mainLayout.setObjectName("mainLayout")
        self.label_title = QtWidgets.QLabel(FormUpdateUser)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.mainLayout.addWidget(self.label_title)
        self.groupBox_update_user = QtWidgets.QGroupBox(FormUpdateUser)
        self.groupBox_update_user.setObjectName("groupBox_update_user")
        self.formLayout = QtWidgets.QVBoxLayout(self.groupBox_update_user)
        self.formLayout.setObjectName("formLayout")
        self.label_id = QtWidgets.QLabel(self.groupBox_update_user)
        self.label_id.setObjectName("label_id")
        self.formLayout.addWidget(self.label_id)
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.lineEdit_id = QtWidgets.QLineEdit(self.groupBox_update_user)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.searchLayout.addWidget(self.lineEdit_id)
        self.pushButton_cari = QtWidgets.QPushButton(self.groupBox_update_user)
        self.pushButton_cari.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_cari.setObjectName("pushButton_cari")
        self.searchLayout.addWidget(self.pushButton_cari)
        self.formLayout.addLayout(self.searchLayout)
        self.label_nama = QtWidgets.QLabel(self.groupBox_update_user)
        self.label_nama.setObjectName("label_nama")
        self.formLayout.addWidget(self.label_nama)
        self.lineEdit_nama = QtWidgets.QLineEdit(self.groupBox_update_user)
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.formLayout.addWidget(self.lineEdit_nama)
        self.label_username = QtWidgets.QLabel(self.groupBox_update_user)
        self.label_username.setObjectName("label_username")
        self.formLayout.addWidget(self.label_username)
        self.lineEdit_username = QtWidgets.QLineEdit(self.groupBox_update_user)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.formLayout.addWidget(self.lineEdit_username)
        self.label_password = QtWidgets.QLabel(self.groupBox_update_user)
        self.label_password.setObjectName("label_password")
        self.formLayout.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(self.groupBox_update_user)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.formLayout.addWidget(self.lineEdit_password)
        self.label_level = QtWidgets.QLabel(self.groupBox_update_user)
        self.label_level.setObjectName("label_level")
        self.formLayout.addWidget(self.label_level)
        self.comboBox_level = QtWidgets.QComboBox(self.groupBox_update_user)
        self.comboBox_level.setObjectName("comboBox_level")
        self.comboBox_level.addItem("")
        self.comboBox_level.addItem("")
        self.formLayout.addWidget(self.comboBox_level)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.addItem(spacerItem)
        self.pushButton_update_user = QtWidgets.QPushButton(self.groupBox_update_user)
        self.pushButton_update_user.setObjectName("pushButton_update_user")
        self.formLayout.addWidget(self.pushButton_update_user)
        self.mainLayout.addWidget(self.groupBox_update_user)
        self.bottomLayout = QtWidgets.QHBoxLayout()
        self.bottomLayout.setObjectName("bottomLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout.addItem(spacerItem1)
        self.pushButton_kembali = QtWidgets.QPushButton(FormUpdateUser)
        self.pushButton_kembali.setObjectName("pushButton_kembali")
        self.bottomLayout.addWidget(self.pushButton_kembali)
        self.mainLayout.addLayout(self.bottomLayout)

        self.retranslateUi(FormUpdateUser)
        QtCore.QMetaObject.connectSlotsByName(FormUpdateUser)

    def retranslateUi(self, FormUpdateUser):
        _translate = QtCore.QCoreApplication.translate
        FormUpdateUser.setWindowTitle(_translate("FormUpdateUser", "Update User"))
        self.label_title.setStyleSheet(_translate("FormUpdateUser", "font-size: 36px; font-weight: bold; color: white; margin-bottom: 20px;"))
        self.label_title.setText(_translate("FormUpdateUser", "Update User"))
        self.groupBox_update_user.setTitle(_translate("FormUpdateUser", "Edit Data User"))
        self.label_id.setText(_translate("FormUpdateUser", "Cari ID User:"))
        self.lineEdit_id.setPlaceholderText(_translate("FormUpdateUser", "Masukkan ID..."))
        self.pushButton_cari.setText(_translate("FormUpdateUser", "🔍 Cari"))
        self.label_nama.setText(_translate("FormUpdateUser", "Nama Baru:"))
        self.lineEdit_nama.setPlaceholderText(_translate("FormUpdateUser", "Nama Lengkap"))
        self.label_username.setText(_translate("FormUpdateUser", "Username Baru:"))
        self.lineEdit_username.setPlaceholderText(_translate("FormUpdateUser", "Username"))
        self.label_password.setText(_translate("FormUpdateUser", "Password Baru:"))
        self.lineEdit_password.setPlaceholderText(_translate("FormUpdateUser", "Kosongkan jika tidak diubah"))
        self.label_level.setText(_translate("FormUpdateUser", "Level Akses:"))
        self.comboBox_level.setItemText(0, _translate("FormUpdateUser", "User"))
        self.comboBox_level.setItemText(1, _translate("FormUpdateUser", "Admin"))
        self.pushButton_update_user.setText(_translate("FormUpdateUser", "💾 Simpan Perubahan"))
        self.pushButton_kembali.setText(_translate("FormUpdateUser", "Kembali"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormUpdateUser = QtWidgets.QWidget()
    ui = Ui_FormUpdateUser()
    ui.setupUi(FormUpdateUser)
    FormUpdateUser.show()
    sys.exit(app.exec_())
